### PR TITLE
Update install instructions for .NET 6.0

### LINKED ISSUE #1012: Outdated build instructions, build broken with dotnet-sdk 3.1
Build error with dotnet-sdk 3.1:
```
SDK Version: 3.1.415
...
/nix/store/bkil2pn0r10zy1i3919qg36nn2gb81qw-dotnet-sdk-3.1.415/sdk/3.1.415/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/btcpayserver/BTCPayServer/BTCPayServer.csproj]

Build FAILED.
```

Affected pages:
```
./docs/Deployment/ManualDeploymentExtended.md  (Many references)
./docs/Deployment/ManualDeployment.md          (Many references)
./docs/Contribute/DevCode.md:                  (1. [.NET Core SDK 3.1+](https://dotnet.microsoft.com/download))
./docs/Development/Altcoins.md                 (Instead, install [.NET Core 3.1 SDK](https://www.microsoft.com/net/download/windows))
./docs/Development/LocalDev.md                 ([.NET Core 3.1 SDK](https://dotnet.microsoft.com/download))
```

### PR DESCRIPTION
**Pull request by dennisreimann**
Closes #1012.

### CODE REVIEW

**Comment by dennisreimann** [comment]
Do the updated instructions work for you, @erikarvstedt?

**Comment by erikarvstedt** [comment]
I haven't tested the `apt`-based install instructions because I'm [using nix](https://github.com/NixOS/nixpkgs/pull/157707) for building btcpayserver.
But grepping shows that all references to dotnet 3.1 were changed to 6.0. Thanks!
I'm not approving yet because of the test failure.

**Comment by dennisreimann** [comment]
The test failures are unrelated, the dead link check is a bit unreliable, but the links changed here are good. 

@NicolasDorier please give it a short review so that we can update the instructions now that .NET 6 is required.

**Review by erikarvstedt — APPROVED** [review]

**Comment by NicolasDorier** [comment]
@erikarvstedt btw, we fixed this https://github.com/btcpayserver/btcpayserver/issues/1894 in the 1.4.0, this is relevant to your Nix project.

**Pull request merged**
