### PR TITLE
Lightning node store setup updates

### LINKED ISSUE #879: Restructure Lightning Network page to correspond to the new UI
In https://github.com/btcpayserver/btcpayserver/pull/2348 we changed the famous `click here` link for the LN. We should restructure LN doc and FAQ to correspond to this new change.

### PR DESCRIPTION
**Pull request by britttttk**
Close #879

### CODE REVIEW

**Comment by britttttk** [comment]
Wow this Q&A is really really old. https://docs.btcpayserver.org/FAQ/FAQ-LightningNetwork/#i-previously-installed-btcpayserver-without-lightning-can-i-enable-it lol

**Review by Zaxounette — COMMENTED** [review]
ACK the wording.
tACK the image changes since I have a nitpick for you.

You used the build with the new headers included for the screenshots, which it nice since it'll save us some time by not having to update those tomorrow.
But since those headers now only have the custom title that one gives the store, a simple title like "test" can be confusing in a screenshot.

Something as generic as `My First Store` should do.

**Comment by britttttk** [comment]
>Something as generic as My First Store should do. 

Yeah test looks a bit strangely placed without any context that it is the store name. I agree, good idea. @Zaxounette I will update it

**Comment by Zaxounette** [comment]
I just reported that white dot not being centered in the [UI](https://chat.btcpayserver.org/btcpayserver/pl/nccwumqgytdmtmjbcfsyd57ccr) channel.
Thanks for making me see this Britt, now it that's not fixed it'll trigger me for eternity !

**Comment by britttttk** [comment]
> white dot not being centered

@Zaxounette I was only saying that I covered the "U" with my red box. But that white dot, I think it was just an issue in my image quality possibly

image

**Comment by Zaxounette** [comment]
No I can reproduce, it's not your image quality.

**Review by Zaxounette — APPROVED** [review]
LGTM ! 
Thanks for the "My First Store" change :)

**Review by dennisreimann — APPROVED** [review]

**Pull request merged**
