### PR TITLE
add how to forward ports with a reverse SSH tunnel

### PR DESCRIPTION
**Pull request by openoms**
Adding the copy of the page from my tutorials which came to be when I was setting up a self-hosted BTCpay on my hack0: https://github.com/openoms/bitcoin-tutorials/blob/master/ssh_tunnel.md

The setup is running non-stop since weeks now without issues.

Any advice to modify, update and link in specific places is welcome.

### CODE REVIEW

**Comment by Kukks** [comment]
This is invaluable, awesome  stuff

**Comment by Kukks** [comment]
Do you think we could extend this eventually to somehow allow multiple tunnels and forward the ports domain on domain origin? That way we'd be able to offer some kind of service for multiple BTCPay home devices

**Comment by pavlenex** [comment]
@britttttk any idea where we can nest this doc? I'm thinking under changedomain.md, it's more of an advanced doc. Or should it be just put in FAQ instead of having a separate page?

**Comment by britttttk** [comment]
I'm a fan of making it's own doc.
Possibly put under it development section on docs.btcpayserver.org. 

@pavlenex I would avoid adding it to the changedomain.md doc because noobs are confused of that process already. For FAQ I would add a link for reverse SSH tunnel but we can add to FAQ after merge.

**Comment by pavlenex** [comment]
>  Possibly put under it development section on docs.btcpayserver.org.

Or under Raspberry Pi? 
@openoms which section makes more sense to you?

**Comment by Kukks** [comment]
I would do a separate doc. and eventually create a "Accessing your BTCPay installation" which links this, dynamic dns, mDnS(.local domains, there is some trickery here for windows that's undocumented)

**Comment by openoms** [comment]
> Do you think we could extend this eventually to somehow allow multiple tunnels and forward the ports domain on domain origin? That way we'd be able to offer some kind of service for multiple BTCPay home devices

Not sure of what are you thinking of here. The ssh tunnel is running on the BTCPay host, so a VPS could take many tunnels (limited by port numbers) and may be channel them to the specific domain with Nginx?

This is might be what ShiftCrypto is doing for the BitBoxBases called Shift Connect: https://base.shiftcrypto.ch/networking.html

**Comment by pavlenex** [comment]
I just have no clue where this should be link on GitBook so that it does not confuse people. I can merge it as it is, but this doc won't be visible on docs.btcpayserver.org unless you add a link to it in summary.md

**Comment by openoms** [comment]
Could be nested under `deployment`.  There could be an extra layer with advanced deployment options this being one. There could be a page about Tor as well as that topic is not covered in the docs much.

**Comment by pavlenex** [comment]
Ok merging this for now, and will figure out how to link it in GitBook later on.

**Comment by pavlenex** [comment]
Added a new section that now looks like this.
Screenshot 2020-01-03 at 17 24 26

**Pull request merged**
