### PR TITLE
FAQ Deployment.md - Update code snippet

### LINKED ISSUE #756: Outdated folder reference on Documentation
I found the documentation points to a folder that is not the right one.

Specifically this site:
https://docs.btcpayserver.org/FAQ/FAQ-Deployment/#how-to-access-the-onion-address-without-clearnet

image

That folder change  = /BTC-P2P/

### PR DESCRIPTION
**Pull request by Zaxounette**
Closes #756 

This is based on #756 and informations given in the issue.

Review highly recommended since I'm not that tech savvy.

### CODE REVIEW

**Comment by Zaxounette** [comment]
`├─BROKEN─ https://electrondust.com/2017/11/25/setting-raspberry-pi-wifi-static-ip-raspbian-stretch-lite/ (BLC_UNKNOWN)`

Unrelated to this PR.

**Comment by dennisreimann** [comment]
The information is correct as it is, see my issue comment.

**Comment by dennisreimann** [comment]
Closing as the associated issue has also been closed. Thanks nevertheless @Zaxounette 🍰

**Comment by Zaxounette** [comment]
@dennisreimann Noted ! :)

**Pull request closed without merging**
