### PR TITLE
adding Node.JS example documentation

### PR DESCRIPTION
**Pull request by paulwillen**

### CODE REVIEW

**Comment by dennisreimann** [comment]
@paulwillen Hey, thanks for the contribution! Can you give me access to your fork, so that I can push [some minor modifications](https://github.com/dennisreimann/btcpayserver-doc/tree/paulwillen/master)?

**Comment by paulwillen** [comment]
@dennisreimann I hope I did the right thing - Added you as a collaborator to my fork.. Let me know if I did it right.

**Comment by dennisreimann** [comment]
Thanks @paulwillen, everything OK. I messed up afterwards and had to open and merge #1205, because this one got closed when I pushed to your remote.

Hope that's OK, thanks again for the contribution!

**Comment by paulwillen** [comment]
Yup - No problem - main thing is that the documentation is better now....

**Pull request closed without merging**
