### PR TITLE
Set BTCPAY_ENABLE_SSH=true in Raspberry Pi deployment guides

### PR DESCRIPTION
**Pull request by wiz**
Screen Shot 2019-10-11 at 14 05 51

### CODE REVIEW

**Comment by dennisreimann** [comment]
Is this a new setting? I could not find it in the docs – what does this exactly do?

**Comment by britttttk** [comment]
@dennisreimann check out [btcpayserver-docker readme](https://github.com/btcpayserver/btcpayserver-docker) for environment variable descriptions.

**Comment by dennisreimann** [comment]
Thanks @britttttk! Alright, will add this to my own configs as well – looks good!

**Comment by pavlenex** [comment]
Specifically, you can read about the new env variable [here](https://blog.btcpayserver.org/1-0-3-132-released/).

**Pull request merged**
