### PR TITLE
Big commerce documentation

### PR DESCRIPTION
**Pull request by TChukwuleta**
Include Big commerce docs 

cc. @pavlenex

### CODE REVIEW

**Comment by pavlenex** [comment]
I don't see it in the sidebar?

Screenshot 2024-09-26 at 11 35 53

**Comment by TChukwuleta** [comment]
I put it under plugins

**Comment by TChukwuleta** [comment]
Updated @pavlenex

**Comment by pavlenex** [comment]
Does it only work with 2.0.0? @TChukwuleta ? If so we should probably say that in prerequisites.

**Comment by TChukwuleta** [comment]
It works with previous version (1.3 )and also 2.0... It was implemented before 2.0 , however it is compatible with 2.0

But yea, I'd include that in the docs

**Comment by pavlenex** [comment]
Alright, happy to merge once you're ready.

**Comment by pavlenex** [comment]
@TChukwuleta closing this one since it's already done on #[1414](https://github.com/btcpayserver/btcpayserver-doc/pull/1415)

**Comment by TChukwuleta** [comment]
Hey @pavlenex  the reference PR #1415  is for Odoo.. while this is for BigCommerce

**Comment by pavlenex** [comment]
My bad  @TChukwuleta! Re-opened.

**Comment by pavlenex** [comment]
@TChukwuleta If we add 2.0.0 as requirement, I believe we can merge this one.

**Comment by TChukwuleta** [comment]
Yea... We can

**Comment by TChukwuleta** [comment]
Hey @pavlenex .. Updated the ReadMe with the required version. 

image

**Pull request merged**
