### PR TITLE
Basic info page about API keys

### PR DESCRIPTION
**Pull request by woutersamaey**
Comes in handy when we need to explain API keys and where to find them.
Some apps that need an API key can link to this page.

### CODE REVIEW

**Comment by Zaxounette** [comment]
I feel like expanding on an already existing doc would be best for this paragraphe.

[This doc](https://docs.btcpayserver.org/GreenFieldExample/#create-a-new-api-key) covers the basics (and an example) of the Greenfield API.
Your paragraphe could be integrated in it.

Changing the actual title of that page could make sense as well, to reflects the added information.

**Comment by woutersamaey** [comment]
@Zaxounette I don't mind moving the content, only the page you're mentioning is a technical page (it talks about cURL), whereas the page I'm thinking of would be for users who don't know what APIs are. They'd only know they need to go somewhere, click a few buttons and permissions and copy the key.

Zapier wants a page like that in your docs so it can be referenced to users as they're trying to figure out what an "API Key" even means.

**Comment by Zaxounette** [comment]
Your comment makes sense.

That being said, API key settings are nested inside the user settings.

We actually have no page relating to those options (password, FIDO/2FA, API keys, etc...) under user settings.
I propose that you nest your document under `FAQ and common issues` in the config.js file, and inside the FAQ folder. `FAQ-UserSettings.md` could be an appropriate name.

That way you link to your section on that page in Zapier.

If you want to add the basic info for the rest of the user settings, go ahead, otherwise i'll do it once your PR is merged.

**Comment by britttttk** [comment]
> expanding on an already existing doc would be best for this paragraphe

agree, this does not seem to need a new doc, adding to FAQ seems better

**Comment by dennisreimann** [comment]
@woutersamaey Can you move it to the FAQ as suggested?

**Comment by pavlenex** [comment]
ping @woutersamaey what do we want to do with this one? Is it still relevant?

**Comment by woutersamaey** [comment]
@pavlenex yeah we're still going to need it for Zapier's docs. They desire a doc page that explains API keys... I'll rededicate myself to this task.

**Comment by woutersamaey** [comment]
Not needed anymore.

**Pull request closed without merging**
