### PR TITLE
Update Hardware as a Service page

### PR DESCRIPTION
**Pull request by AaronDewes**
This updates the Umbrel link to their latest website.

Also, a warning should be added for Umbrel. A lot of people are running a shop on Umbrel without realizing Umbrel prohibts commercial use of their software. Using an Umbrel node to sell anything is commercial use.

### CODE REVIEW

**Comment by pavlenex** [comment]
@lukechilds is this true? I just don't see how selling products via btcpay violates Umbrel's license?

**Comment by AaronDewes** [comment]
According to their license, Umbrel can only be used for noncommercial purposes, selling something clearly is commercial. Maybe I'm misinterpreting their license though, I'm not a lawyer.

**Comment by lukechilds** [comment]
Nah, this isn’t something that’s prohibited. So all good. Here’s the license [FAQ](https://github.com/getumbrel/umbrel/wiki/License-FAQ).

**Comment by pavlenex** [comment]
Thanks for clarifying @lukechilds.
@AaronDewes how about we remove the warning and add a new link then? Also we can add runcitadel there right? I don't think we reference to it but you can run btcpay on it, correct?

**Comment by AaronDewes** [comment]
I also noticed the RaspiBlitz link leads to the Fulmo shop, which sells prebuilt RaspiBlitz nodes. Maybe https://raspiblitz.org/ would be a better link?

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
