### PR TITLE
Re-arrange the hardware documentation

### PR DESCRIPTION
**Pull request by NicolasDorier**
Ping @Bangalisch, @danielcharrua, @dennisreimann 

This is a follow up of https://github.com/btcpayserver/btcpayserver-doc/pull/1148 .

1. I have moved the documentation of cloudflare to the hardware category, as there is no real advantage to use it elsewhere.
2. I renamed the sections concerning solutions to expose your server on internet
3. Changed `Hardware.md` so it isn't an introduction of a specific hardware deployment, and instead an introduction to the three solutions we are documenting.

### CODE REVIEW

**Comment by dennisreimann** [comment]
I think it's a bit unfortunate that the categorization now initially hides e.g. the Raspberry Pi deployment, which people might be looking for. We could set [collapsible](https://vuepress.vuejs.org/theme/default-theme-config.html#sidebar-groups) to false to circumvent that issue.

Also: Shouldn't we group the web/cloud deployments like this as well?

**Comment by NicolasDorier** [comment]
Yes I think we should, but in another PR.

Myself I only know Lunanode, whereas there are quite a lot of options nowadays I'd like we have at a single place documented.

**Review by dennisreimann — APPROVED** [review]

**Comment by dennisreimann** [comment]
Yup, works for me!

I'll move the Azure and Google Cloud docs into Web Deployment in a separate PR tomorrow.

**Comment by danielcharrua** [comment]
great job guys! looks much better to me now

**Pull request merged**
