### PR TITLE
Include plugins in nav as external

### PR DESCRIPTION
**Pull request by TChukwuleta**
@ndeet  included plugins documentations for some other plugins as external links in the plugin navs

### CODE REVIEW

**Comment by dennisreimann** [comment]
Why not integrate them directly, like we did with [the other ones](https://github.com/btcpayserver/btcpayserver-doc/blob/master/setup-deps.sh#L284)?

**Comment by TChukwuleta** [comment]
yea.. I think that'd be cooler.

I'd update it

**Comment by ndeet** [comment]
Yes that would also work, then add it to Plugins section in the sidebar like [this](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/.vuepress/config.js#L130)

**Comment by TChukwuleta** [comment]
made the update @dennisreimann  @ndeet 

You can take another look

**Comment by dennisreimann** [comment]
Very good! Only thing I saw: There seems to be something funky going on with the first headline of the [https://deploy-preview-1410--btcpayserver-docs-preview.netlify.app/SideShift/](SideShift) and [https://deploy-preview-1410--btcpayserver-docs-preview.netlify.app/DynamicReports/])Dynamic Reports) plugins. Their source looks fine though.

**Comment by ndeet** [comment]
Yes, those two headlines seem to have some formatting issue, maybe some whitespace in front or at the end of the headlines?

I would also add rockstardev's [Payroll plugin](https://github.com/rockstardev/BTCPayServerPlugins.RockstarDev/tree/master/Plugins/BTCPayServer.RockstarDev.Plugins.Payroll) and Nicolas [Boltcard plugin](https://github.com/NicolasDorier/boltcards-plugin)

**Comment by TChukwuleta** [comment]
Sideshift and Dynamic reports are fine now. I removed unprintable characters from readme


I'd add the payroll and the boltcard plugin

**Comment by TChukwuleta** [comment]
Hey @ndeet  I think we can merge this for now. There is an issue with Boltcard ReadMe file. Tried reformatting and all but not still working but other ReadMe file works

I would probably open a PR on the plugin. But I believe we are good to go on the others including payroll plugin

**Comment by pavlenex** [comment]
LGTM. Great improvements @TChukwuleta 🎉 Some of these require cleanups (the readme's) but that's unrelated to this PR.

**Pull request merged**
