### PR TITLE
Add a new BTCPay third-party host

### PR DESCRIPTION
**Pull request by lawgate2019**
LAWGATE.io has successfully set up a self-hosted BTCpayserver instance with working email for password recovery. At this point we would like to open it for people who don't want to go thru the hassle of running their own instance.

### CODE REVIEW

**Comment by Eskyee** [comment]
great looking site, but don't look like btcpay third-party host, ??? @lawgate2019

**Comment by lawgate2019** [comment]
Thanks!
 
The BTCpay is linked in this section on the site:

PAY WITH BITCOIN THRU SELF-HOSTED BTCPAY

Clients can pay in Bitcoin (BTC) which is processed directly & securely through our BTCPayserver. We offer support and free-hosting for anyone who wants to try out BTCPayserver.org for their own business without going thru the hassle of setting up a BTCpayinstance. If you want to start using BTCpay for your business, just sign-up right here!

The word here contains the direct link to our BTCpay server.

We intentionally did not wanted to link to the BTCpay as we think it is beneficial for users to know a bit of background.
Albeight we are a young business, we are incorporated in Switzerland and have office space there.
Thanks for your understanding, Stefan

**Comment by lawgate2019** [comment]
Hi there
Link has been changed to the registration page of our BTCpay server.
Also it is ordered alphabetically.

**Comment by pavlenex** [comment]
Thanks for making the changes and congratz on your first PR here 👍

**Comment by lawgate2019** [comment]
Thanks a lot! We really like BTCpayserver🥇and keep recommending it to our clients as well.

**Pull request merged**
