### PR TITLE
Managed btcpay

### PR DESCRIPTION
**Pull request by LinoxBE**
As discussed in Slack, adding the managed BTCPay servers to the docs.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Can you would call it "Third party hosted BTCPay servers" and explain why a merchant would want it?

**Comment by LinoxBE** [comment]
I'll change the naming, sounds good. But regarding hy a merchant would want it, quickly becomes marketing (in my eyes, at least). I'm not sure that you want that on such a page.

What makes more sense then maybe, is that every service/host adds 1 phrase behind his URL, highlighting why people should click there?

**Comment by NicolasDorier** [comment]
This is not marketing. Hosting your own server is more complicated than just using a third party host. With third party host you know you have somebody to contact and help if something goes wrong.

**Comment by LinoxBE** [comment]
Here we go. What do you think? Simple but straight-forward.

**Comment by LinoxBE** [comment]
I forgot to change the title to "Third party hosted BTCPay servers". Should be good now.

**Comment by NicolasDorier** [comment]
I am back to code, will be more reactive next time :p

**Comment by LinoxBE** [comment]
No problem, it wasn't critical :-p

I hope that you enjoyed your time with your fresh wife, and your family ;-)

**Pull request merged**
