### PR TITLE
Integrate configurator docs

### PR DESCRIPTION
**Pull request by dennisreimann**
Builds on #751 and integrates the external configurator docs.

Closes #751.

### CODE REVIEW

**Comment by britttttk** [comment]
@dennisreimann thanks for this PR!

**Review by Kukks — APPROVED** [review]

**Comment by pavlenex** [comment]
@dennisreimann Tests are failing for this one?

**Comment by dennisreimann** [comment]
Yes, I'm currently on the failing tests :)

**Comment by dennisreimann** [comment]
Thanks @pavlenex for merging btcpayserver/btcpayserver-configurator#16 – now the tests and link check work :)

**Pull request merged**
