### PR TITLE
Integrate Vault docs

### PR DESCRIPTION
**Pull request by dennisreimann**
I've added them to the Features section -- I think it fits there, but I'm open for other suggestions.

### CODE REVIEW

**Comment by dennisreimann** [comment]
Edit: I just saw we have the Hardware Wallet Integration page, which wasn't linked anywhere. I guess this will need some clarifying discussion on what to integrate where.

**Review by Zaxounette — APPROVED** [review]
The placement works perfectly for me!

**Comment by dennisreimann** [comment]
Linkcheck fixes included in btcpayserver/BTCPayServer.Vault#37

We can continue here once that one is merged.

**Comment by pavlenex** [comment]
Should we nest this under `Wallet`?

**Comment by dennisreimann** [comment]
I've now restructured the nav and separated the two concerns:

- HWW Integration got added under Wallet, where it fits nicely and also covers the Vault from an end user's perspective
- Moved the freshly integrated Vault docs inside the Development section, because they are rather technical and don't contain much information for the end user

We can also merge this PR before the other one in the Vault repo, this way I can clean up the links and references there and point to the appropriate new pages in the docs.

**Comment by pavlenex** [comment]
@dennisreimann Linkcheck reporting broken links :

```
Getting links from: http://localhost:8080/Vault
50
├─BROKEN─ http://localhost:8080/BTCPayServer.Hwi (HTTP_404)
51
├─BROKEN─ http://localhost:8080/BTCPayServer.Vault (HTTP_404)
52
├─BROKEN─ http://localhost:8080/features/vault (HTTP_404)

```

It also doesn't look like all the pages are there? https://deploy-preview-955--btcpayserver-docs-preview.netlify.app/HardwareWalletIntegration/

**Comment by dennisreimann** [comment]
@pavlenex yes, see my comment above, the links are fixed in the Vault repo PR. :)

**Pull request merged**
