### PR TITLE
Add and suggest Matomo as analytics

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
[Matomo](https://matomo.org/) is free, open source, self-hosted and privacy-oriented.
We should add and suggest it to analytics FAQ

### CODE REVIEW

**Comment by esky33kubernetes** [comment]
We don’t need any tracking or cookies tools 🍪 here 😆 just add it to your own fork 🧐

**Comment by esky33kubernetes** [comment]
This ain’t bitpay 🤓

**Comment by RiccardoMasutti** [comment]
@esky33kubernetes
I'm not referring about tracking BTCPay website or documentation.

In the docs there's a FAQ on how to insert Google Analytics on stores. I just think that it'll be better to advice something open source and privacy oriented like Matomo.

And, btw, analytics are essential to ecommerce and shops to boost sells.

**Comment by esky33kubernetes** [comment]
Sorry 👍 I misunderstood your suggestion!! 
Cheers

**Comment by esky33kubernetes** [comment]
I agree we should always help the merchants 🙌

**Comment by esky33kubernetes** [comment]
Free and open source code makes this possible ❤️

**Comment by pavlenex** [comment]
As a part of pull-request cleanup I am closing this PR since it seems there's no will/time to continue amending it. 

I'll close it for now. If in future you wish to work on it, feel free to re-open.

**Pull request closed without merging**
