### PR TITLE
Unprivileged user creation

### PR DESCRIPTION
**Pull request by GraemeConradie**
useradd -m (create home), -s (shell) /dev/null is not valid, must be sudo useradd -M (no home) admin && sudo usermod -L (lock account) admin

### CODE REVIEW

**Comment by Zaxounette** [comment]
Pinging the code enabled peeps @dennisreimann and @britttttk .

Is this a correct bash string change ?

**Comment by dennisreimann** [comment]
Why does the account get locked?

**Comment by GraemeConradie** [comment]
> Why does the account get locked?

Service accounts don't have a "proper" login shell, i.e. they have /usr/sbin/nologin as login shell (or, back in the old days, /bin/false). Service accounts should be locked, i.e. it is not possible to login (for traditional /etc/passwd and /etc/shadow).

This can be achieved in different ways, MatterMost suggests : sudo useradd --system --user-group mattermost, RocketChat on the otherhand uses : sudo useradd -M rocketchat && sudo usermod -L rocketchat.

I prefer -M -L, and assigning ownership to the required directories and files.

**Comment by dennisreimann** [comment]
Ok, thanks for elaborating, I learned something today! 👍

**Review by dennisreimann — APPROVED** [review]
ACK.

**Pull request merged**
