### PR TITLE
[MERGE AFTER 2.0] Remove docs on customizing checkout page

### PR DESCRIPTION
**Pull request by TChukwuleta**
Based on the [BTCPay Server 2.0: Megathread](https://github.com/btcpayserver/btcpayserver/issues/5899#top) , part of the task is to Remove docs on https://docs.btcpayserver.org/Development/Theme/#checkout-page-themes

This PR tends to resolve it, by removing the path from the side bar so that it is not accessible

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Why not removing the article itself and the images?

**Comment by TChukwuleta** [comment]
I wasn't sure so sure, that's why I didn't remove it. I would do that.


Yea, I'm aware that it's after 2.0 merge. Thank you

**Review by dennisreimann — CHANGES_REQUESTED** [review]
I dont think we should completely remove the page, but most of it. We should keep the "Developing and extending a custom theme" part and adapt it to what we've added with the branding options. 

Can you re-add that page with the "Developing and extending a custom theme" only (until "2. Bootstrap themes") and I can adjust it from there? Thanks!

**Comment by TChukwuleta** [comment]
Sure @dennisreimann

**Comment by TChukwuleta** [comment]
Updated @dennisreimann

**Review by dennisreimann — APPROVED** [review]
Adapted it to fit with the current state.

**Review by pavlenex — APPROVED** [review]

**Comment by pavlenex** [comment]
**To be merged when 2.0 is out.**

**Comment by pavlenex** [comment]
@dennisreimann mentioned 

> The doc in the PR version is a refresher about customizing the server theme, imho it can get merged right away.

I agree with this, @NicolasDorier ?

**Comment by NicolasDorier** [comment]
Seems good to me

**Pull request merged**
