### PR TITLE
Introduce Mattermost

### PR DESCRIPTION
**Pull request by pavlenex**
This PR remove Slack links and references, fixes few small typos and adds a new section for finding an issue by searching through the Mattermost in Troubleshooting.md

### CODE REVIEW

**Comment by NicolasDorier** [comment]
You deleted a whole file (FAQ.md)

**Comment by pavlenex** [comment]
@NicolasDorier yes it's useless, we have now /FAQ folder it's duplicate all of the questions are in /FAQ

**Comment by NicolasDorier** [comment]
@pavlenex in this case you need to update the links in https://github.com/btcpayserver/btcpayserver because the help links point to the FAQ page.

**Comment by pavlenex** [comment]
Are you referring to readme or the tooltips you've added? AFAIK all tool-tips in the UI lead to /FAQ. 

I mainly left the FAQ.md for this long because some questions from NBItstack linked to there, but since we removed the Wiki, I thought it's good to remove legacy page.

**Comment by NicolasDorier** [comment]
Indeed, nothing point to FAQ.md

**Pull request merged**
