### PR TITLE
deprecate direct Ledger integration in Ledger.md and Wallet.md

### LINKED ISSUE #549: Ledgerwallet.md - Ledger support discontinued
Direct Ledger wallet support has been discontinued. People can of course still use Ledger with BTCPay Vault.

We should figure out if we should remove that page entirely or put a warning that it's a legacy feature.

### PR DESCRIPTION
**Pull request by pavlenex**
- Adds the  warrnign in Ledger.md and provides solutions for people that may have been using the integration.
- Removes the mention of "sign with ledger" in Wallet.md

ledger

Note createwallet.md is a broken link, this PR should be merged after #550 

Closes #549

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Mmh should we say deprecated? This is not deprecated this is not supported.

**Comment by pavlenex** [comment]
@NicolasDorier  You're right. I went with deprecated because in a way we're replacing it with Vault
```
In the world of software development, "deprecated" refers to functions or elements that are in the process of being replaced by newer ones.
```
But `no longer supported` seems more accurate.

Are other instructions okay? Hopefully I didn't miss anything.

**Comment by britttttk** [comment]
@pavlenex should we mention Vault [here?](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/FAQ/FAQ-Wallet.md#how-to-connect-my-wallet-to-btcpay-server) also is this [Why is my Ledger not detected by BTCPay Server](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/FAQ/FAQ-Wallet.md#why-is-my-ledger-not-detected-by-btcpay-server) still needed?

**Comment by pavlenex** [comment]
> 
> 
> @pavlenex should we mention Vault [here?](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/FAQ/FAQ-Wallet.md#how-to-connect-my-wallet-to-btcpay-server) also is this [Why is my Ledger not detected by BTCPay Server](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/FAQ/FAQ-Wallet.md#why-is-my-ledger-not-detected-by-btcpay-server) still needed?

I think we should focus on cleaning the Wallet-FAQ once we decide on the structure in #550 

I'll remove that particular FAQ now, nicely spotted.

**Comment by pavlenex** [comment]
Actually there's too much work for FAQ-Wallet cleaning ,beyond the scope of this PR. I'd do this in a separate issue/pull request.

**Pull request merged**
