### PR TITLE
Add NBXplorer docs

### PR DESCRIPTION
**Pull request by dennisreimann**
Simply adds the docs from the NBXplorer repo to the developer section. [Preview](https://deploy-preview-1160--btcpayserver-docs-preview.netlify.app/NBXplorer/)

Requires an update for the file paths once dgarage/NBXplorer#371 has been merged.

### CODE REVIEW

**Comment by dennisreimann** [comment]
@NicolasDorier The NBXplorer README and a unit test reference a `Design.md`, which seems to be gone. Was it renamed/moved or deleted?

**Comment by pavlenex** [comment]
ping @NicolasDorier Check this comment https://github.com/btcpayserver/btcpayserver-doc/pull/1160#issuecomment-1242181482

**Comment by dennisreimann** [comment]
Let's get the NBXplorer docs update merged first, so that I can update this one.

**Comment by NicolasDorier** [comment]
The Design.md was removed because the design is now different with the postgres backend.

**Pull request merged**
