### PR TITLE
Odoo docs integration

### LINKED ISSUE #1414: Add Odoo Documentation to the docs
Similar to #1380 and many others.

We have Odoo Repository https://github.com/btcpayserver/odoo once @ndeet adds docs to readme, that repo should be reflected in our docs.

### PR DESCRIPTION
**Pull request by TChukwuleta**
Resolves #1414 

Integrates Odoo documentattion directly from https://github.com/btcpayserver/odoo

### CODE REVIEW

**Comment by pavlenex** [comment]
Duplicate of https://github.com/btcpayserver/btcpayserver-doc/pull/1415? Up to @ndeet.

**Comment by TChukwuleta** [comment]
Ohh...  I thought Ndeet pushed directly to this:https://github.com/btcpayserver/odoo

**Comment by pavlenex** [comment]
@TChukwuleta Should we make Odoo17 default and link back to Odoo16 from that doc?

Check how @ndeet did it here https://github.com/btcpayserver/btcpayserver-doc/pull/1415#issuecomment-2228907230

https://deploy-preview-1415--btcpayserver-docs-preview.netlify.app/Odoo/

Screenshot 2024-10-01 at 11 42 06

Happy to merge once this is addressed.

**Comment by TChukwuleta** [comment]
I see that Odoo 17 is live. https://docs.btcpayserver.org/Odoo/

Was thinking @ndeet could we have both 17 and 16 in the same readme but seperated into sections. Going to be a long ReadMe. 

But that way all the information that a customer would need for Odoo installation (whether 16 or 17) is accessible

**Comment by pavlenex** [comment]
I am closing this one, 17 links to 16 already.

**Pull request closed without merging**
