### PR TITLE
Fix supporters partial and remove it from Forms page

### LINKED ISSUE #1459: Local deployment issues
For some reason there are several issues with local deployment on the main branch:

1. There's no explore by topic our supporters in the index page
2. Integration, plugins in the sidebar aren't rendered locally even with `setup dependencies` run
Screenshot 2024-11-18 at 13 59 47
Screenshot 2024-11-18 at 13 59 54

### PR DESCRIPTION
**Pull request by dennisreimann**
Maybe the Vuepress dev build didn't like the whitespaces inside the SVG and the mixed indentation in the HTML part.

Works for me locally now and fixes #1459.

Removed the supporters partial from the Forms page, because I assume it was a copy&paste leftover.

### CODE REVIEW

**Comment by ndeet** [comment]
Thanks! Fixes the bug for me on the frontpage but not on Guide.md here http://localhost:8081/Guide/

**Comment by pavlenex** [comment]
Yeah integration section is still broken locally, and it's definetely not done in #1457 as it was there before that.

Screenshot 2024-11-18 at 16 08 56

**Comment by ndeet** [comment]
@pavlenex interesting, for me integrations and plugins work unlike on your screenshot. Did you modify anything? Normally happens for me when I mess some menu link up. For me only the /Guide/ seems to be broken atm.

**Comment by ndeet** [comment]
Damn cache, it works now :+1: :hugs:

**Comment by pavlenex** [comment]
Nuked every possible thing, cleared cache, updated everything, nodejs v.22

Guide page is back! So it was cache/nodejs issue probably. 

However plugins and integrations aren't which must be related to ` ./setup-deps.sh` script.

When I run it I get this 

Screenshot 2024-11-18 at 17 42 35

Which could lead you to believe there are no errors, but if you check the last line it says

```
sed: 1: "/Users/p/Downloads/btcp ...": extra characters at the end of p command
```
I have no idea what that means but that's the only thing from my logs that are akward when setting things up.

Full logs
```
etup dependency: BTCPayServer
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Setup dependency: NBXplorer
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Setup dependency: Vault
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Setup dependency: Configurator
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Setup dependency: Docker
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Setup dependency: Transmuter
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Setup dependency: Zapier
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Setup dependency: PodServer
Cloning into '/Users/p/Downloads/btcpayserver-doc-2/deps/podserver'...
remote: Enumerating objects: 152, done.
remote: Counting objects: 100% (152/152), done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 152 (delta 45), reused 90 (delta 24), pack-reused 0 (from 0)
Receiving objects: 100% (152/152), 430.69 KiB | 1.91 MiB/s, done.
Resolving deltas: 100% (45/45), done.
Setup dependency: LNDhub API
Cloning into '/Users/p/Downloads/btcpayserver-doc-2/deps/lndhub-api'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 33 (delta 1), reused 20 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (33/33), 208.20 KiB | 947.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Setup dependency: Trocador
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Setup dependency: Drupal
Already on '8.x-1.x'
Your branch is up to date with 'origin/8.x-1.x'.
Already up to date.
Setup dependency: Smartstore
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Setup dependency: Grandnode
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Setup dependency: Nopcommerce
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Setup dependency: Wix
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Setup dependency: Xenforo
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Setup dependency: Odoo 16 and 17
Already on '17.0'
Your branch is up to date with 'origin/17.0'.
Already up to date.
Setup dependency: Kukks' plugins
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
sed: 1: "/Users/p/Downloads/btcp ...": extra characters at the end of p command
p@Pavles-MacBook-Air btcpayserver-doc-2 % 
```

@dennisreimann any ideas?

**Comment by dennisreimann** [comment]
It looks like you are running into this: https://stackoverflow.com/questions/39325759/sed-on-mac-extra-characters-after-p-command

Can you pull again, run `./setup-deps.sh` again and see if it is now fixed?

**Comment by pavlenex** [comment]
Works now! 🚀

**Comment by ndeet** [comment]
@pavlenex tried to reproduce by deleting deps folder and running, setup-deps.sh and it worked for me. Maybe try to `rm -f deps` folder and run deps script again.

**Pull request merged**
