### PR TITLE
Contribute/WriteDocs.md § addition + Contribute/README.md finalization

### PR DESCRIPTION
**Pull request by Zaxounette**
Part of #671 

* Deletes paragraphes in `Contribute/README.md` that are now used in other Contribute documentation
* Adds links to relevant contributing types docs + community for help

As per https://github.com/btcpayserver/btcpayserver-doc/pull/704#issuecomment-691387429 and https://github.com/btcpayserver/btcpayserver-doc/issues/671#issuecomment-691437421 :
* Adds relative URL paragraphe in `Contribute/WriteDocs.md`
* Adds link to Vuepress markdown documentation for relative URL's.

### CODE REVIEW

**Comment by Zaxounette** [comment]
@dennisreimann I suspect the linkcheck is a false positive ?

ContributeDesign.md, it's not merged yet ( #705 ) so obviously it's reporting as broken. That I consider normal behavior.

But Community.md works fine in local. So I don't know for that one.

**Comment by dennisreimann** [comment]
The linkcheck runs against the current version of the PR, so it reports a correct state: those pages seem to be missing.

**Comment by Zaxounette** [comment]
> The linkcheck runs against the current version of the PR, so it reports a correct state: those pages seem to be missing.

That's true for ContributeDesign.md, that's why I reported that I consider it a normal behavior.

But Community.md exists and has existed since the docs inception.

**Comment by dennisreimann** [comment]
> But Community.md exists and has existed since the docs inception and the link works for me in local VS Code.

The trailing slash here is the problem:

```markdown
hit the [community](../Community.md/) with your questions.
```

It needs to be `[community](../Community.md)`

**Comment by Zaxounette** [comment]
Alright ! 
Good to go.
When #705 is merged, it'll resolve the build fail.

All other broken links have been fixed.

Thanks @dennisreimann =)

**Review by pavlenex — APPROVED** [review]

**Comment by Zaxounette** [comment]
^ Rebase

**Comment by Zaxounette** [comment]
`├─BROKEN─ https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=1766%3A1005 (HTTP_404)`

This link works, so false positive.

**Review by pavlenex — APPROVED** [review]

**Comment by dennisreimann** [comment]
Added Figma to the exclude list, the link works.

**Pull request merged**
