### PR TITLE
Adding odoo to docs.

### PR DESCRIPTION
**Pull request by ndeet**

### CODE REVIEW

**Comment by pavlenex** [comment]
LGTM, But I assume our goal is to update those docs? Should we merge it once updated?

**Comment by ndeet** [comment]
I updated them and created separate one for the 17.0 branch as the process is slightly different, before I created this PR.

**Comment by ndeet** [comment]
Which means all ready to go and announce.

**Comment by pavlenex** [comment]
So what should we do, here's what I see:
Screenshot 2024-07-15 at 18 24 12
Should we default to 17 with a link to 16, this doc seems quite oudated in terms of graphics at least 😆

**Comment by pavlenex** [comment]
Here you go @ndeet , not perfect but will do the job for now.

Odoo-16

Odoo-17

**Comment by pavlenex** [comment]
@ndeet there's a conflict now FYI.

**Pull request merged**
