### PR TITLE
WIP - Contribute.md refactoring - Config.js

### PR DESCRIPTION
**Pull request by Zaxounette**
This is a WIP proposal for #671 

See commit comments for details.

### CODE REVIEW

**Comment by pavlenex** [comment]
The way I suggest  we approach this, since it's quite a big change, is to add one contribute.md at a time. For example do a PR for ContributeTranslate.md then ContributeSEO.md etc. Then at the end we can do the structure and change contribute.md itself. This help us have pages under the hood until we get to the big picture and tie it all together.

But structure-wise this is indeed what I have in mind. We just first have to see how to define steps and processes for every page.

**Comment by Zaxounette** [comment]
Okay, no problem on the multiple PR's.

**Comment by Zaxounette** [comment]
^ Revert docs and folder creation since each doc will be created in corresponding PR's.

**Comment by Zaxounette** [comment]
Closing, working on this from another angle.

**Pull request closed without merging**
