### PR TITLE
docs(altcoin-faq): add missing word

### PR DESCRIPTION
**Pull request by escapedcat**

### CODE REVIEW

**Comment by escapedcat** [comment]
@pavlenex right, forgot about that, thx. done.

**Comment by Kukks** [comment]
I would avoid merging this unless there is a way to allow the old link to exist to route to the new one.

**Comment by escapedcat** [comment]
Hm, it's just an anchor-jump-link. The new one will still point to the correct file at least.  

How are the docs being deployed? Maybe we could add a `div id="how-to-an-altcoin-in-btcpay"` around it here https://github.com/btcpayserver/btcpayserver-doc/pull/389/files#diff-ae48f5bfe6bc26f84e69040465540d98R32 to keep the old link working?

**Comment by pavlenex** [comment]
@Kukks I don't think this is a problem at all.
@escapedcat It's auto-deployed via GitBook.

**Pull request merged**
