### PR TITLE
Add a network diagram

### PR DESCRIPTION
**Pull request by dltxio**
I can add some more graphics if you like, but this shows the components and ports etc.

### CODE REVIEW

**Comment by pavlenex** [comment]
I like this one!
@NicolasDorier can you take a look just to make sure it's all good, looks good to me.

**Comment by pavlenex** [comment]
Good point, both diagrams look great together.
@dltxio I'd love to see more of these for sure :)

**Comment by NicolasDorier** [comment]
1. The bitcoin core node is not exposed externally
2. It is not clear where the nginx reverse proxy is. In the diagram it looks like it is between btcpay and nbxplorer

**Comment by dltxio** [comment]
> Good point, both diagrams look great together.
> @dltxio I'd love to see more of these for sure :)

No worries!  I have a few clients im rolling btc pay server out too.  So any content / docs I use for the proposals Im happy to share.

**Comment by dltxio** [comment]
>     1. The bitcoin core node is not exposed externally, but the diagram show it does
> 
>     2. It is not clear where the nginx reverse proxy is. In the diagram it looks like it is between btcpay and nbxplorer

Good feedback, I can amend.

**Comment by NicolasDorier** [comment]
@dltxio can I ask you how we can edit this graph and with which tool you did it?

**Comment by pavlenex** [comment]
As a part of pull-request cleanup I am closing this PR since it seems there's no reply from @dltxio nor the time to amend the changes, so I'll close it for now. If in future you wish to work on it, feel free to re-open.

**Comment by NicolasDorier** [comment]
If you don't have the time, please let me know how you created your diagram, I would like to finish it.

**Pull request closed without merging**
