### PR TITLE
Update FAQ-Deployment.md - add Uninstall BTCPay Server (docker version)

### PR DESCRIPTION
**Pull request by maltokyo**
Add uninstall method for docker version

### CODE REVIEW

**Comment by maltokyo** [comment]
@pavlenex @britttttk should be good now, please take a look.

**Comment by NicolasDorier** [comment]
Awesome thanks for that @maltokyo seems good to me.

**Comment by pavlenex** [comment]
@maltokyo Since it's FAQ, can you please add a link back to[ FAQ-Readme ](https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ/readme.md)since that's our Table of Content then we're good to merge this.

**Comment by maltokyo** [comment]
@britttttk I dont get it, but when I changed file it made new PR.  For future how do I get it into same PR?  Anyway, changes above are done, here and in new PR https://github.com/btcpayserver/btcpayserver-doc/pull/414
Thanks!

**Comment by britttttk** [comment]
@maltokyo did you make changes to a branch? I think if you are making changes to master it makes a new PR but looks like you lost your FAQ changes in the new PR :)

**Comment by britttttk** [comment]
@maltokyo Ah i see what you did, ok should be fine will just merge both.

**Pull request merged**
