### PR TITLE
Add Payment Requests Doc

### PR DESCRIPTION
**Pull request by britttttk**
#187 Payment Requests Doc

### CODE REVIEW

**Comment by NicolasDorier** [comment]
btw, let's not forget to add links here and there in BTCPay interface which point to the doc.

**Comment by pavlenex** [comment]
@NicolasDorier 

Agreed, if you want this particular one can be added next to create payment request button.

Screen Shot 2019-03-12 at 13 36 43

We also have [Apps.md](https://docs.btcpayserver.org/features/apps)

Screen Shot 2019-03-12 at 13 37 03

**Comment by NicolasDorier** [comment]
Or will add.

**Comment by NicolasDorier** [comment]
done

**Pull request merged**
