### PR TITLE
add Trocador to existing plugins

### PR DESCRIPTION
**Pull request by saltrafael**

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]

**Comment by dennisreimann** [comment]
Thanks! Do you also want to add the project's README to the plugin docs?

See PodServer for an example:

- https://github.com/btcpayserver/btcpayserver-doc/blob/master/setup-deps.sh#L213
- https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/.vuepress/config.js#L116

**Comment by saltrafael** [comment]
Sorry for the delay @dennisreimann, like so?

**Review by dennisreimann — APPROVED** [review]
Yes, thanks!

**Comment by dennisreimann** [comment]
And btw don't forget to add the URL as the docs link in the plugin builder: https://docs.btcpayserver.org/Trocador/

**Pull request merged**
