### PR TITLE
Shopify docs cleanup

### PR DESCRIPTION
**Pull request by ndeet**
- Fix steps numbering; 
- Fix steps, add more info; 
- Remove duplicate img/Shopify directory and files.

Related to #1352 and PR #1396 

cc @pavlenex

### CODE REVIEW

**Comment by ndeet** [comment]
Not sure why image 11 and 12 don't show up, seems all other images are cached and have some string attached but not those two new files. I would assume it will work and is just a quirk in netlify.

**Comment by pavlenex** [comment]
@ndeet LGMT for images perhaps folder lower/uppercase difference?
Screenshot 2024-05-08 at 17 37 06

**Comment by ndeet** [comment]
@pavlenex what I did was deleted "Shopify" with the two 11 + 12 images and then did new screenshots and put them into "shopify" folder with a new file extension of .png. The images show up locally so I think it is fine. Maybe you can pull and run npm run start to double check?

**Comment by ndeet** [comment]
@pavlenex found the problem, forgot to but ./ to make image path relative, fixed now also in preview.

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
