### PR TITLE
Linkcheck 404 - Update broken link

### PR DESCRIPTION
**Pull request by Zaxounette**
* Updates the link to new functional one
* Edits one title and a sentence to reflect name change in OS.

### CODE REVIEW

**Comment by Zaxounette** [comment]
OMG @dennisreimann , all the twitter links in every single page report a 404.

Twitter isn't down, so false alarm, but why did it happen ?

**Comment by dennisreimann** [comment]
It looks like they have rate limited the requests …

**Comment by Zaxounette** [comment]
> It looks like they have rate limited the requests …

Noted.
Should they then be excluded ?
I expect they will be reported at each and every PR now if they limited the requests like you said.

**Comment by dennisreimann** [comment]
Ok, [tried again](https://github.com/btcpayserver/btcpayserver-doc/runs/1574764815?check_suite_focus=true), let's add twitter.com to the excludee list then.

**Comment by dennisreimann** [comment]
Now it works again :)

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
