### PR TITLE
Add InvoiceNinja integration document

### PR DESCRIPTION
**Pull request by pavlenex**
Add invoice ninja doc and removes DreamLab img folder since we no longer have that integration.

PR Preview https://deploy-preview-1411--btcpayserver-docs-preview.netlify.app/InvoiceNinja/

### CODE REVIEW

**Comment by pavlenex** [comment]
@TChukwuleta here's a PR I've tested it locally and imo all seems OK, once you have a pr for btcpayserver.org link to https://docs.btcpayserver.org/Deployment/InvoiceNinja/

**Comment by pavlenex** [comment]
@TChukwuleta Merged so you can do your PR on btcpayserver.org to add InviceNinja as an integration, the link as I said above is https://docs.btcpayserver.org/Deployment/InvoiceNinja/

**Comment by TChukwuleta** [comment]
alrightt

**Comment by pavlenex** [comment]
Ouups my bad https://docs.btcpayserver.org/InvoiceNinja/ sorry @TChukwuleta should be good now!

**Comment by TChukwuleta** [comment]
yea.. it is. thanks

**Pull request merged**
