### PR TITLE
Update each doc for standardization

### PR DESCRIPTION
**Pull request by Zaxounette**
This PR aims to standardize the usage of `BTCPay Server` instead of just `BTCPay`.
**Review should not be hindered by the multiple commits because it fixes this and only this.**

_Note:_ Not a single title will be changed, as to not break multiple links.

PS: Any docs not appearing as a commit in this PR has been reviewed but had no changes needed.

### CODE REVIEW

**Comment by Zaxounette** [comment]
Ready for review.
You can hate me now !

**Comment by pavlenex** [comment]
Is there really a need for this? Sometimes it's just wordiness to say btcpay server. Also conflict in  docs/LocalDevelopment.md

**Comment by pavlenex** [comment]
After thinking a bit, I want to NACK this. Sometimes it's just hard to read sentences where btcpay server is mentioned a few times, btcpay or btcpay server is the same thing.

**Comment by Zaxounette** [comment]
1°) 
> Sometimes it's just hard to read sentences where btcpay server is mentioned a few times,

Agreed.
Made me think of another approach to tackling this.
This PR can be closed, and in regards to your comment, i'd link to work on reducing the number of `btcpay`, `BTCPay`, `BTCPay Server` in sentences/docs, as there is way too much of them.

2°)
> btcpay or btcpay server is the same thing.

I don't agree with this.
`BTCPay Server is the product/service, as `BTCPay`, `btcpay` is a kind of slang (noun), that IMHO shouldn't be in official docs/papers or other writings.

I also recall Nicolas writing that it's BTCPay Server, not BTCPay. I'd have to find where I saw it, it was some time ago.
Hence why I standardize everywhere I can into BTCPay Server.

**Comment by pavlenex** [comment]
Unfortunately me you or Nicolas don't define how people will call it, it's people who decide how they want to call sth.

**Pull request closed without merging**
