### PR TITLE
Dev docs

### PR DESCRIPTION
**Pull request by dennisreimann**
This appends the "How to manually test payments" from the [BTCPayServer.Tests/README.md](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer.Tests/README.md#how-to-manually-test-payments) to the LocalDevelopment.md – I think this is useful information worth having on that page.

Also adds a new page "Security Disclosures", based on the [SECURITY.md](https://github.com/btcpayserver/btcpayserver/blob/master/SECURITY.md) from the BTCPay Server repo.

### CODE REVIEW

**Comment by pavlenex** [comment]
> Also adds a new page "Security Disclosures", based on the SECURITY.md from the BTCPay Server repo.

Hm do we really need this one in the docs? I assume majority of security researches are familiar with the process, may just seem as irrelevant info for regular devs. Or is there a good reason why we want it in?

**Comment by dennisreimann** [comment]
We can remove it, made it a separate commit because I wasn't sure either, but wanted to discuss it. What do you think, @NicolasDorier?

We should also wait for btcpayserver/btcpayserver#1762 being merged.

**Comment by NicolasDorier** [comment]
I think that's not a problem to have this info in both the doc and in the repo.
Also, not a problem to maintain thanks to the system of dennis.

**Comment by dennisreimann** [comment]
@pavlenex let's get this merged. If you'd like to see the security page removed let me know.

**Comment by NicolasDorier** [comment]
oops conflict.

**Comment by dennisreimann** [comment]
I think with the recent changes to this document and the addition of the link to the tests README, this PR is obsolete.

**Comment by dennisreimann** [comment]
Rebased and updated, so that the content from the Tests README replaces the current "Test utilities" section. Basically this inlines the information that we otherwise link to.

**Pull request merged**
