### PR TITLE
Changes to the TryItOut page according the roadmap

### PR DESCRIPTION
**Pull request by Bangalisch**
Yo, 

All most fully revised the TryItOut page. 
Just missing some Visual content, still running the old video on there. 

Moved the Testnet stuff to its own page in the Deployment tab. 
As the TryItOut as there to just get someone to quickly try it and i dont think a Testnet Environment goes with that. 

Its a Quick walk trough the first steps on setting it up on our Demo. 
And right after that we point towards Third-partys and their deployments and ofc encourage to use those. 

i did keep the Live demo parts about the POS to test out. 
Its at the bottom after one has gone trough the setup and maybe picked a third-party.

### CODE REVIEW

**Comment by Bangalisch** [comment]
https://github.com/btcpayserver/btcpayserver-doc/issues/998

**Comment by Bangalisch** [comment]
Added the flow in Refunds page according https://github.com/btcpayserver/btcpayserver-doc/issues/919

**Comment by pavlenex** [comment]
@Bangalisch Thanks for these. Please in the future, it's good practice to tackle issues in a separate PR, it makes it easier to review and when less files are involved, less things can go wrong. 

A few things before I start reviewing:
- There was a minor conflict in your PR so I resolved it and pushed.
- The test are failing with this error:
```
11:23:20 AM: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
11:23:20 AM: (Source code omitted for this binary file)
11:23:20 AM:  @ ./docs/Refund.md?vue&type=template&id=7b279522& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"163db298-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/.vuepress/preprocessMarkdown.js!./docs/Refund.md?vue&type=template&id=7b279522&) 1:2363-2404
11:23:20 AM:  @ ./docs/Refund.md?vue&type=template&id=7b279522&
11:23:20 AM:  @ ./docs/Refund.md
11:23:20 AM:  @ ./node_modules/@vuepress/core/.temp/internal/page-components.js
11:23:20 AM:  @ ./node_modules/@vuepress/core/lib/client/util.js
11:23:20 AM:  @ ./node_modules/@vuepress/core/lib/client/app.js
11:23:20 AM:  @ ./node_modules/@vuepress/core/lib/client/serverEntry.js
11:23:20 AM:  @ multi ./node_modules/@vuepress/core/lib/client/serverEntry.js
11:23:20 AM: Error: Failed to compile with errors.
11:23:20 AM:     at /opt/build/repo/node_modules/@vuepress/core/lib/node/build/index.js:190:16
11:23:20 AM:     at finalCallback (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:254:12)
11:23:20 AM:     at /opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:277:6
11:23:20 AM:     at done (/opt/build/repo/node_modules/neo-async/async.js:2931:13)
11:23:20 AM:     at runCompilers (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:181:48)
11:23:20 AM:     at /opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:188:7
11:23:20 AM:     at /opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:270:7
11:23:20 AM:     at finalCallback (/opt/build/repo/node_modules/webpack/lib/Compiler.js:257:39)
11:23:20 AM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:273:13
11:23:20 AM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
11:23:20 AM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
11:23:20 AM:     at onCompiled (/opt/build/repo/node_modules/webpack/lib/Compiler.js:271:21)
11:23:20 AM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:681:15
11:23:20 AM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
11:23:20 AM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
11:23:20 AM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:678:31
11:23:20 AM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
11:23:20 AM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
11:23:20 AM:     at /opt/build/repo/node_modules/webpack/lib/Compilation.js:1423:35
11:23:20 AM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
11:23:20 AM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
11:23:20 AM:     at /opt/build/repo/node_modules/webpack/lib/Compilation.js:1414:32
11:23:20 AM:     at eval (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
11:23:20 AM:     at /opt/build/repo/node_modules/terser-webpack-plugin/dist/index.js:321:9
11:23:20 AM:     at step (/opt/build/repo/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
11:23:20 AM:     at done (/opt/build/repo/node_modules/terser-webpack-plugin/dist/TaskRunner.js:98:30)
11:23:20 AM:     at tryCatcher (/opt/build/repo/node_modules/cacache/node_modules/bluebird/js/release/util.js:16:23)
11:23:20 AM:     at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/cacache/node_modules/bluebird/js/release/promise.js:547:31)
```
@dennisreimann any idea what's wrong here?

**Comment by dennisreimann** [comment]
The error comes from having uppercased file extensions (like `.JPG` instead of `.jpg`) - Vuepress doesn't like that.

Other than that: Please also remove the added `.DS_Store` files. Those should be added to a [global gitignore file](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c).

**Comment by pavlenex** [comment]
Yeah I figured, there are some more things that are causing tests to fail, it's a nightmare to figure out when there are so many different parts, I'lll ping @Bangalisch so we can split it up in two PR's.

**Comment by pavlenex** [comment]
Yeah I figured, there are some more things that are causing tests to fail, it's a nightmare to figure out when there are so many different parts, I'lll ping @Bangalisch so we can split it up in two PR's.

**Comment by pavlenex** [comment]
Yeah I figured, there are some more things that are causing tests to fail, it's a nightmare to figure out when there are so many different parts, I'lll ping @Bangalisch so we can split it up in two PR's.

**Pull request closed without merging**
