### PR TITLE
Wallet docs update

### LINKED ISSUE #1294: IMG update on wallet settings doc
Yo

mostly as reminder or small task for someone to swap the image that goes below the topic of using camera to scan QR. 
It shows a wallet rescan instead of camera feature. 

https://docs.btcpayserver.org/Wallet/#camera-qr-scan

### PR DESCRIPTION
**Pull request by TChukwuleta**
Resolves #1294 
Updating the wallet documentation images with what is currently available. Also did some reorder of the content, plus included some new content e.g. labels

### CODE REVIEW

**Comment by pavlenex** [comment]
@TChukwuleta can you look why the tests are failing?

**Comment by TChukwuleta** [comment]
Woops.. Alright.

I'd take a look

**Comment by TChukwuleta** [comment]
Hey @pavlenex  you can go ahead and review. All is good now

**Review by pavlenex — APPROVED** [review]
Good work @TChukwuleta, looks good to me!

**Pull request merged**
